In [36]:
import numpy as np

## Solving the following equations

### Consistent system of equations with exactly one solution
$$\begin{eqnarray}
2p - 3q &=& 3\\
4p - 5q + r &=& 7\\
2p - q - 3r &=& 5\\
\end{eqnarray}$$


### Consistent system of equations with infinitely many solutions
$$\begin{eqnarray}
4p - 5q + r &=& 7\\
8p - 10q + 2r &=& 14\\
12p - 15q + 3r &=& 21\\
\end{eqnarray}$$

Another example would be :
$$\begin{eqnarray}
x + y + z &=& 2\\
2x + 2y + 2z &=& 4\\
\end{eqnarray}
$$

Even though,<br>
    **no of unknowns > no of equations**<br>
still we have a solution.

### Inconsistent system of equations ( system of equations with No Solution such as 2 parallel lines/planes )
$$\begin{eqnarray}
x + y &=& 2\\
x + y &=& 3\\
\end{eqnarray}$$

 ## Expressing above system of equations in Ax = b form

In [87]:
'''Coefficient Matrix'''

''' Consistent System '''

''' Exactly one solution '''
#A = np.array([[2, -3, 0],[4, -5, 1],[2, -1, -3]])
#b = np.array([3,7,5])

''' Infinitely many solutions '''

''' Case 1 : number of unknowns = number of equations '''
#A = np.array([[4, -5, 1], [8, -10, 2], [12, -15, 3]])
#b = np.array([7, 14, 21])

''' Case 2 : number of unknowns > number of equations '''
A = np.array([[1,1,1], [2,2,2]])
b = np.array([2,4])

''' Inconsistent system of equations '''
#A = np.array([[1, 1], [1, 1]])
#b = np.array([2, 3])

x = np.zeros_like(b)

''' Solution can exist even when number of unknowns is more than number of equations. '''
# assert A.shape[1] == b.shape[0], "Matrix vector multiplication cannot be performed."

print("Matrix A")
print(A)
print("Vector b")
print(b)
print("Vector x")
print(x)

Matrix A
[[1 1 1]
 [2 2 2]]
Vector b
[2 4]
Vector x
[0 0]


## Forward Elimination

In [94]:
''' Last row is never the pivot row. Therefore, range(A.shape[0])'''
no_of_rows_became_all_zero = 0
no_solution = False
for pivot_row_index in range(A.shape[0]):
    print()
    print("Pivot row number:{}".format(pivot_row_index+1))
    print(A[pivot_row_index,:], b[pivot_row_index])
    ''' np.any returns False if all the elements in an array are zeros '''
    if not np.any(A[pivot_row_index,:]): 
        if not np.any(b[pivot_row_index]):
            ''' Only if both LHS and RHS are equal to zero, then the 2 lines/planes completely overlap each other'''
            print("Equation number {} is a linear multiple of Equation number {}".format(pivot_row_index+1, pivot_row_index))
            no_of_rows_became_all_zero = no_of_rows_became_all_zero + 1
        else:
            print("Inconsistent system of equations found. This system has NO SOLUTION.")
            no_solution = True
            break
    else:
        for other_row_index in range(pivot_row_index+1, A.shape[0]):
            '''In python 3.x, 4/2 is floating point division, 4//2 is integral division.'''
            #print("Denominator:{}".format(A[pivot_row_index, pivot_row_index]))
            #print("Numerator:{}".format(A[other_row_index, pivot_row_index]))
            #print("Divison:{}".format(A[other_row_index, pivot_row_index]/A[pivot_row_index, pivot_row_index]))
            pivot_element = A[pivot_row_index, pivot_row_index]
            print("Pivot Element:{}".format(pivot_element))
            multiplier = A[other_row_index, pivot_row_index]/A[pivot_row_index, pivot_row_index]
            print("Multiplier {}".format(multiplier))
            A[other_row_index, :] = A[other_row_index, :] - multiplier * A[pivot_row_index, :]
            b[other_row_index] = b[other_row_index] - multiplier * b[pivot_row_index]
            
assert not no_solution, "NO SOLUTION!!!"


Pivot row number:1
[1 1 1] 2
Pivot Element:1
Multiplier 0.0

Pivot row number:2
[0 0 0] 0
Equation number 2 is a linear multiple of Equation number 1


## Coefficient Matrix A and vector b after Forward Elimination

In [89]:
print("Matrix A")
print(A)
'''Vector b after Forward Elimination'''
print("Vector b")
print(b)

Matrix A
[[1 1 1]
 [0 0 0]]
Vector b
[2 0]


# Back Substitution

## Dimensional Analysis

In [90]:
# Dimensions of Coefficient Matrix A
print("Dimensions of A")
print(A.shape)
# Dimensions of vector b
print("Dimensions of b")
print(b.shape)

Dimensions of A
(2, 3)
Dimensions of b
(2,)


## Solving for p, q and r
For equation,
$$\begin{eqnarray}
ap + bq + cr &=& d\\
where, 
   p = \frac{(d - bq - cr)}{a}\\
\end{eqnarray}$$

In [91]:
''' Check if the consistent system of equations have infinitely many solutions.'''
assert no_of_rows_became_all_zero != (A.shape[0]-1), "Consistent system of equations have infinitely many solutions."

AssertionError: Consistent system of equations have infinitely many solutions.

In [93]:
''' For consistent system of equations with a unique solution.'''
''' Solving the equations in a bottom up fashion'''
for i in range(x.shape[0]-1, -1, -1):
    x[i] = (b[i] - np.dot(A[i,i+1:],x[i+1:]))/A[i,i]
print(x)

ValueError: shapes (1,) and (0,) not aligned: 1 (dim 0) != 0 (dim 0)