In [3]:
''' https://docs.scipy.org/doc/numpy/reference/generated/numpy.ravel.html '''

' https://docs.scipy.org/doc/numpy/reference/generated/numpy.ravel.html '

In [18]:
import numpy as np
''' np.ravel converts n-dimensional numpy array to 1-dimensional numpy array'''

' np.ravel converts n-dimensional numpy array to 1-dimensional numpy array'

In [19]:
x = np.ravel([1,2,3]) #(3,) remains (3,)
print(x)
print(x.shape)

[1 2 3]
(3,)


In [20]:
y = np.ravel([[1,2,3]]) # (1,3) to (3,)
print(y)
print(y.shape)

[1 2 3]
(3,)


In [21]:
z = np.ravel([[[1,2,3]]]) # (1,1,3) to (3,)
print(z)

[1 2 3]


In [22]:
a = np.ravel([[1,2], [3,4], [5,6]]) # (3,2) to (6,)
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [23]:
p = np.ravel([[0.1, 0.2, 0.3, 0.4, 0]])
print(p)
print(p.shape)

[ 0.1  0.2  0.3  0.4  0. ]
(5,)
