In [3]:
''' https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.random.choice.html '''
import numpy as np

In [5]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [10]:
# Choose k numbers out of np.arange(5) randomly WITH REPLACEMENT. So in the output same number may come more than once
k = 3 # output shape => (3,)
r = np.random.choice(5, k) # 5 by default implies np.arange(5), each of 5 numbers can be chosen with equal probablity
print(r) # 1-dimensional


[4 2 1]


In [14]:
# In case you want to choose k numbers out of np.arange(5) randomly with varied probablity WITH REPLACEMENT
p = [0.1, 0.2, 0.3, 0.4, 0] # sum of probablities must be equal to 1
rp = np.random.choice(5, k, p=p) # where k is the output shape
print(rp) # 1-dimensional

[3 2 3]


In [15]:
b = np.random.choice([10,20,30,2,3], k) # Choose k elements out of the given list, each element of list has equal probablity to be chosen
print(b)

[30  3 20]


In [16]:
c = np.random.choice(np.array([1,5,10,14,21]), k) # With replacement
print(c)

[21  1 21]


In [18]:
# What happens with 2-dimensional array?
# d = np.random.choice(np.array([ [1,2,4] ]), k) # Error, np.random.choice works only with 1-dimensional array
# print(d)

In [19]:
d = np.random.choice(range(5), k)
print(d) # Output shape => (k, ) => (3, )

[0 4 0]


In [21]:
output_shape = (1,3)
e = np.random.choice(range(5), output_shape)
print(e)
print(e.shape)

[[3 3 4]]
(1, 3)


In [22]:
# What happens if Output shape is not mentioned? What is the default value?
f = np.random.choice(range(5))
print(f) # returns a single value in case output shape is not mentioned
print(f.shape)

4
()


In [24]:
# Can p be a anything but 1-dimensional array? NO
# p = np.array([[0.1, 0.2, 0.3, 0.4, 0]]) # 2-dimensional array
# g = np.random.choice([1,2,3,4,5], p=p) # Error
# print(g)

ValueError: a must be 1-dimensional

In [25]:
# Convert n-dimensional numpy array to 1-dimensional array
p = np.array([[0.1, 0.2, 0.3, 0.4, 0]])
p = np.ravel(p) # (5,)
g = np.random.choice(np.array([1,2,3,4,5]), p = p)
print(g) # Since output_shape is not mentioned, therefore it returns one value.

1
